# Write your query or mutation here
query findPublishedPosts {
  publishedPosts(first: 20, orderBy: { field: title, direction: desc }) {
    edges {
      node {
        ...PostData
        author {
          ...UserData
          posts {
            ...PostData
          }
        }
      }
    }
    pageInfo {
      endCursor
      hasNextPage
      hasPreviousPage
      startCursor
    }
    totalCount
  }
}

fragment PostData on Post {
  id
  createdAt
  updatedAt
  title
  content
  published
}

fragment UserData on User {
  id
  createdAt
  updatedAt
  email
  firstname
  lastname
  role
}
